image: bradrydzewski/ruby:2.1.0
env:
  - RAILS_ENV=test
services:
  - postgres
script:
  - echo 'ggggg'
  - sudo mkdir -p /var/run/postgres
  - ps -A
  - psql -p 5432 -h localhost -U postgres -c 'create database test;'