image: bradrydzewski/ruby:2.1.0
env:
  - RAILS_ENV=test
services:
  - postgres
script:
  - echo 'ggg'
  - sudo mkdir -p /var/run/postgres
  - ls -la /etc/init.d
  - psql -p 5432 -h localhost -U postgres -c 'create database test;'